"""empty message

Revision ID: 4b4ea9759605
Revises: 
Create Date: 2024-05-25 20:37:40.025772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4ea9759605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_label', sa.String(), nullable=False),
    sa.Column('account_class', sa.Enum('BALANCE_SHEET', 'INCOME_STATEMENT', name='accountclass'), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype'), nullable=False),
    sa.PrimaryKeyConstraint('account_id', name=op.f('pk__ledger_account')),
    sa.UniqueConstraint('account_name', name=op.f('uq__ledger_account__account_name'))
    )
    op.create_table('ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__ledger_entry'))
    )
    op.create_table('ledger_entry_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEBIT', 'CREDIT', name='type'), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_account.account_id'], name=op.f('fk__ledger_entry_item__account_id__ledger_account')),
    sa.ForeignKeyConstraint(['entry_id'], ['ledger_entry.id'], name=op.f('fk__ledger_entry_item__entry_id__ledger_entry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__ledger_entry_item'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_entry_item')
    op.drop_table('ledger_entry')
    op.drop_table('ledger_account')
    # ### end Alembic commands ###
