"""empty message

Revision ID: 8e4979afaec7
Revises: 34b9b565e5d9
Create Date: 2024-05-05 23:09:24.812735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4979afaec7'
down_revision = '34b9b565e5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'REVENUE', 'EXPENSE', name='type'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__ledger_account')),
    sa.UniqueConstraint('account', name=op.f('uq__ledger_account__account'))
    )
    with op.batch_alter_table('ledger_entry_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk__ledger_entry_item__account_id__ledger_account'), 'ledger_account', ['account_id'], ['id'])
        batch_op.drop_column('account')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entry_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk__ledger_entry_item__account_id__ledger_account'), type_='foreignkey')
        batch_op.drop_column('account_id')

    op.drop_table('ledger_account')
    # ### end Alembic commands ###
